services:
  bitcoind:
    image: bitcoin/bitcoin:28.0
    container_name: vtxo-bitcoind
    ports:
      - "18443:18443"
    command:
      - bitcoind
      - -regtest
      - -server
      - -rpcuser=vtxo
      - -rpcpassword=vtxo
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
      - -fallbackfee=0.00001
      - -txindex=1
    tmpfs:
      - /root/.bitcoin
